CREATE DATABASE DB_Real_Estate_Strorage;
GO

USE [DB_Real_Estate_Strorage];
GO

CREATE TABLE Person
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(20) NULL,
	LastName NVARCHAR(30) NOT NULL,
	Phone NVARCHAR(13) NULL,
	Mail NVARCHAR(40) NULL
);
GO
CREATE TABLE District
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(25) NOT NULL
);
GO
CREATE TABLE Estate 
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	EstOwner INT NOT NULL,
	Area DECIMAL(4,1) NULL CHECK(Area>0),
	Rooms INT NOT NULL CHECK (Rooms>0),
	District INT NULL,
	Address NVARCHAR(40) NOT NULL,
	Price INT NOT NULL CHECK(Price>0),
	Rent BIT NULL,
	Sale BIT NULL
);
GO

ALTER TABLE Estate
ADD CONSTRAINT FK_Esate_District
FOREIGN KEY(District) REFERENCES District(Id) 
ON DELETE SET NULL
ON UPDATE CASCADE;
GO

ALTER TABLE Estate
ADD CONSTRAINT FK_Esate_Person
FOREIGN KEY(EstOwner) REFERENCES Person(Id) 
ON DELETE NO ACTION
ON UPDATE CASCADE;
GO

CREATE TABLE DBUser
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PersId INT NOT NULL,
	Login VARCHAR(40),
	Password VARCHAR(40)
);
GO

ALTER TABLE dbo.DBUser
ADD CONSTRAINT FK_DBUser_Person
FOREIGN KEY(PersId) REFERENCES dbo.Person(Id) 
ON DELETE CASCADE
ON UPDATE CASCADE;
GO

CREATE TABLE Contracts
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	EmployeeId INT NOT NULL,
	CustomerId INT NULL,
	EstateId INT NOT NULL,
	Date DATE NOT NULL DEFAULT(GETDATE())
);
GO

ALTER TABLE dbo.Contracts
ADD CONSTRAINT FK_Contracts_PersonEmployee
FOREIGN KEY(EmployeeId) REFERENCES dbo.Person(Id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
GO 

ALTER TABLE dbo.Contracts
ADD CONSTRAINT FK_Contracts_PersonCustomer
FOREIGN KEY(CustomerId) REFERENCES dbo.Person(Id)
ON DELETE SET NULL
ON UPDATE NO ACTION;
GO 

ALTER TABLE dbo.Contracts
ADD CONSTRAINT FK_Contracts_Estate
FOREIGN KEY(EstateId) REFERENCES dbo.Estate(Id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
GO 

